<?php

/**
 * @file
 * Contains cfr.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cfr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cfr module.
    case 'help.page.cfr':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CFR code demo module.') . '</p>';
      $output .= '<p>' . t('This module provides the functionality detailed in the Web Developer Test document.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cfr_theme() {
  return [
    'cfr_station_list' => [
        'template' => 'cfr_station_list',
        'variables' => [
            'items' => NULL,
        ],
    ],
    'cfr_station_list_alternate' => [
      'template' => 'cfr_station_list_alternate',
      'variables' => [
        'items' => NULL,
      ],
    ],
  ];
}
